name: CI

on: [push, pull_request, workflow_dispatch]

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - run: python -m pip install nox

      - name: "Run code checks"
        run: nox -s lint
