name: Github release

on:
  push:
    tags:
    - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4

    - name: Github publish
      uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        draft: true
        generateReleaseNotes: true
